import type { Metadata } from "next";
import {Roboto} from "next/font/google"
import "./globals.css";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";

import Header from "./components/Header";

config.autoAddCss = false;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const f_roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={f_roboto.className}
      >
      <Header />
      <div className={"flex"}>
        {children}
      </div>
      </body>
    </html>
  );
}
